[build]
  publish = "Youtube2.0"

[[redirects]]
  from = "/"
  to = "/html/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard%20(copy)"
  to = "/html/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard%20(Copy).html"
  to = "/html/dashboard.html"
  status = 200
  force = true

